export const LOCAL_REQUEST = "LOCAL_REQUEST";
export const LOCAL_SUCCESS = "LOCAL_SUCCESS";
export const LOCAL_FAILURE = "LOCAL_FAILURE";

export const LOCAL_DETAIL_REQUEST = "LOCAL_DETAIL_REQUEST";
export const LOCAL_DETAIL_SUCCESS = "LOCAL_DETAIL_SUCCESS";
export const LOCAL_DETAIL_FAILURE = "ADD_LOCAL";

export const LOCAL_REMOVE = "REMOVE_LOCAL";
export const LOCAL_REMOVE_FAILURE = "ADD_LOCAL";
